// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'select': string;
  'tag': string;
  'tagRow': string;
  'tagRowEditing': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
